#!/usr/bin/env python3

# Creates a random tree
def create_tree():
  import random
  from binarytree import tree

  h = random.randint(0,9)
  mytree = tree(height= h, is_perfect=False)
  print("real height",h) # Check the actual height generated by randint
  #print("the tree",mytree)
  return mytree

# Go through the tree
def traverse_tree(root):
  if root == None:
    return None
  else:
    print(root.value)
  
  traverse_tree(root.left)
  traverse_tree(root.right)

# Find the height of an arbitrary tree
def height_tree(root):

  h = 0

  # Base case, h = 0 if root = none
  if root == None:
    return h
  
  # If there is an additional depth
  else:
    if root.left != None or root.right != None:
      h += 1

  # Recurse to find height of left branch and right branch
  h_left = height_tree(root.left)
  h_right = height_tree(root.right)

  # Picks the branch with the greatest height
  if h_left > h_right:
    return h + h_left
  else:
    return h + h_right

    


root = create_tree()
traverse_tree(root)
print("height", height_tree(root))